name: Test CI

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI working!"